namespace nilnul.time.seq_.ical_._rfc
{
	public interface IRdate0exdate { 
				///The RDATE property specifies additional dates or date-times when the event occurrences should happen. 
				/// For example, RDATE;VALUE=DATE:19970101,19970120.
				/// 
				///  The EXDATE property is similar to RDATE
				///  This must point to a valid instance generated by the recurrence rule.
				///  EXDATE and RDATE can have a time zone, and must be dates (not date-times) for all-day events.
				///  
				///"EXDATE;VALUE=DATE:20150610",
				///
				/// github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/main/services/google.md
				/// 
				/// format: YYYYMMDDTHHmmSSZ/YYYYMMDDTHHmmSSZ
				/// example: dates=20201231T193000Z/20201231T223000Z
				///
				/// datatracker.ietf.org/doc/html/rfc5545
				/// 
				///EXDATE:19960402T010000Z,19960403T010000Z,19960404T010000Z
				///EXDATE;TZID=America/New_York:19970902T090000
				///
				///
				/// stackoverflow.com/questions/60373797/google-calendar-api-recurrent-event-exdate-not-working
				///
				/// Since you provided a dateTime for start and end, you should also provide a dateTime in EXDATE, and the time part should match the one you provided in start. Otherwise, the API won't know what event to exclude.
				/// That is to say, the recurrence should be like this:
				/// "RRULE:FREQ=DAILY;UNTIL=20200229T185959Z;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR,SA,SU",
				/// "EXDATE;TZID=Asia/Karachi:20200225T183000"
				///

				/*stackoverflow.com/questions/56400844/getting-exdate-to-work-when-creating-google-recurring-event

using local time without TZID or Z worked, i. e.

EXDATE:20190617T090000
				 */
	}


}
